### ISSUE TITLE
Override some functions not working, such as read()

### ISSUE THREAD

**Issue by pfsun** [gaffe23/linux-inject#2]
Hi,

Great work. I have tried your code. It works well. However, there is still one problem that I don't know whether your code support? I want to override some functions like read, write, open. So I rewrite these functions and compile to one shared object. And then I use your code to inject this shared object. According to the output, the runtime process will not use these override functions. I also check the maps, the shared object has been loaded into the runtime process. If I use LD_RELAOD, the execution will use these override functions. 

Thank you very much.

**Comment by gaffe23** [comment]
Thanks for the kind words, and I'm glad to hear the tool worked well for you.

You're right, the code currently doesn't support redirecting functions. It only does the injection part for you. Once the shared object is loaded, it's up to you to hook functions and redirect them as you see fit.

At some point I may add hooking functionality, or I might write a sample shared object to demonstrate how you could redirect functions. For now, though, injection is the only thing it does. At the end of the day, it's giving you code execution in the context of the target process, and there is quite a lot you can do with that.

Depending on what you're trying to accomplish, you might be able to get away with just unloading the shared object you're trying to override. You could do that inside your shared object's `constructor` function so that it would unload the other library as soon as the injection is finished.
